Added complete unit tests for SorobanAuthorizationEntry, InvokeHostFunctionOperation and SCVal objects
Beans-BV/dotnet-stellar-sdk pull request #2
Opened 2023-12-15 09:48 UTC by cuongph87

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-12-21 07:46 UTC, jopmiddelkamp requested changes

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AddressTest.cs
> +            var ex = Assert.ThrowsException<InvalidOperationException>(() => new SCAccountId(invalidAccountId));
I think a `FormatException` makes more sense here.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AddressTest.cs
> +            var ex = Assert.ThrowsException<InvalidOperationException>(() => new SCContractId(invalidContractId));
I think a FormatException makes more sense here.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AuthTest.cs
> +        private SorobanAddressCredentials InitCredentials()
```suggestion
        private SorobanAddressCredentials InitSorobanAddressCredentials()
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AuthTest.cs
> +        public void TestAccountAddressSorobanAddressCredentials()
If I look at other test they kind of follow the naming convention as followed: `Test[MethodName][Scenario]`.

This is a simpler format that starts with the word "Test" followed by the method name and a brief description of the scenario.

Example: TestCalculateTaxWithExemptItems

So this method name could be more in line like this.
```suggestion
        public void TestSorobanAddressCredentialsWithValidCredentials()
```

And the next method name could be more like this.
```csharp
        public void TestSorobanAddressCredentialsWithMissingAddress()
```

What are your thoughts on this?

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AuthTest.cs
> +    public class AuthTest
```suggestion
    public class SorobanAuthorizationTest
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +            // Action
I think officially its called `Arrange/Act/Assert` So maybe just a quick find and replace from `// Action` to `// Act` would be nice.

```suggestion
            // Act
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +            var scBool = new SCBool(true);
maybe add here an additional false boolean as well just as a secondary check.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +                Assert.AreEqual(scVec.InnerValue[i].ToXdrBase64(), fromXdrBase64ScVec.InnerValue[i].ToXdrBase64());
Why are we parsing this back to an XDR string again? It feels more logical to check if the types and value matches here right?

I see more tests where this happen. This comment counts for all as I'm not gonna place comments at all of the occurences.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +        public void TestSCLedgerKeyContractInstance()
This is an empty method. Why is that? Is this todo? Or can this be removed?

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +            Assert.AreEqual(contractInstance.Storage.Entries.Length, fromXdrBase64ContractInstance.Storage.Entries.Length);
Should we not also check the executable here?

And only comparing the length of the storage doesn't seem like a valid check/result to me. If I'm wrong and it is maybe add a comment about this Assert explaining why this is a valid check/result.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/ScValTest.cs
> +            Assert.AreEqual(contractInstance.Storage.Entries.Length,
Mabye you can move this code to and `AssertSCMap` method or something? That can be reused in the SCMap test as well as here and the method above.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/operations/InvokeHostFunctionOperationTest.cs
> +                ((SCAccountId)((ContractIDAddressPreimage)operation.HostFunction.ContractIDPreimage).Address)
Maybe we can make this a bit more readable by noting it like this.

```csharp
            
            var contractIdPreimage = (ContractIDAddressPreimage)operation.HostFunction.ContractIDPreimage;
            var decodedContractIdPreimage = (ContractIDAddressPreimage)decodedOperation.HostFunction.ContractIDPreimage;

            var address = (SCAccountId)contractIdPreimage.Address;
            var decodedAddress = (SCAccountId)decodedContractIdPreimage.Address;
            
            Assert.AreEqual(address.InnerValue, decodedAddress.InnerValue);
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/operations/FootprintOperationTest.cs
> +            builder.SetExt(zeroExt);
Could we maybe improve this method name? `SetExt` is not really explanatory.

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/ExtendFootprintOperation.cs
> +        private ExtensionPoint _ext;
```suggestion
        private ExtensionPoint _extensionPoint;
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/ExtendFootprintOperation.cs
> +        public Builder SetExt(ExtensionPoint ext)
```suggestion
        public Builder SetExtensionPoint(ExtensionPoint extensionPoint)
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/ExtendFootprintOperation.cs
> +                throw new InvalidOperationException("Ext cannot be null");
```suggestion
                throw new InvalidOperationException("Ext cannot be null");
```
```suggestion
                throw new InvalidOperationException("Extension point cannot be null");
```

2023-12-21 07:46 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/RestoreFootprintOperation.cs
> +        private ExtensionPoint _ext;
Same like before.
```suggestion
        private ExtensionPoint _extensionPoint;
```

2023-12-21 09:29 UTC, cuongph87 commented on stellar-dotnet-sdk-test/AddressTest.cs
> +            var ex = Assert.ThrowsException<InvalidOperationException>(() => new SCAccountId(invalidAccountId));
How about ArgumentException?

2023-12-21 09:41 UTC, cuongph87 commented on stellar-dotnet-sdk-test/operations/FootprintOperationTest.cs
> +            builder.SetExt(zeroExt);
I was confused too, because the generated class has the property named Ext.

2023-12-22 01:39 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/AddressTest.cs
> +            var ex = Assert.ThrowsException<InvalidOperationException>(() => new SCAccountId(invalidAccountId));
Yes that is good!

2024-01-03 09:28 UTC, jopmiddelkamp approved these changes

2024-01-03 09:28 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/SCVal.cs
> +            throw new ArgumentException("Invalid account id");
```suggestion
            throw new ArgumentException("Invalid account id", nameof(value));
```

2024-01-03 09:28 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/SCVal.cs
> +            throw new ArgumentException("Invalid contract id");
```suggestion
            throw new ArgumentException("Invalid contract id", nameof(value));
```

2024-01-03 13:04 UTC, jopmiddelkamp approved these changes

2024-01-03 13:05 UTC, merged