Added support for LedgerEntry classes, SorobanResources and SorobanTransactionData
Beans-BV/dotnet-stellar-sdk pull request #3
Opened 2024-01-11 07:46 UTC by cuongph87

- Added support for LedgerEntry classes, SorobanResources and SorobanTransactionData.
- Renamed class Signer to SignerUtil.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-11 12:19 UTC, jopmiddelkamp requested changes

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/LedgerEntryTest.cs
> +    private readonly Asset _nativeAsset = Asset.Create("native", null, null);
You can use the `AssetTypeNative` class for this right?

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/LedgerEntryTest.cs
> +            Key = new SCString("key 1"),
Can't we use the string for this and then port it to a SCString when serialising/deserialising it? Same for the uint64 on the next line can't that be a ulong? Or would this make no sense?

This question counts for multiple occurrences.

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/LedgerEntryTest.cs
> +            ExtensionV2 = new AccountEntryExtensionV2
I just now thought about this but do we need these Extension properties in the classes that we define? Can't we just add the properties from all the Extension classes in our classes?

So instead of this:
```csharp
        return new LedgerEntryContractData
        {
            LastModifiedLedgerSeq = 10000,
            LedgerExtensionV1 = _ledgerExtensionV1,
            Key = new SCString("key 1"),
            Value = new SCUint64(1000000),
            Contract = new SCContractId("CAC2UYJQMC4ISUZ5REYB2AMDC44YKBNZWG4JB6N6GBL66CEKQO3RDSAB"),
            Durability = ContractDataDurability.Create(ContractDataDurability.ContractDataDurabilityEnum.PERSISTENT),
            ExtensionPoint = new ExtensionPointZero()
            AccountExtensionV1 = new AccountEntryExtensionV1
            {
                Liabilities = new Liabilities(100, 200),
                ExtensionV2 = new AccountEntryExtensionV2
                {
                    NumberSponsored = 5,
                    NumberSponsoring = 7,
                    SignerSponsoringIDs = signerSponsoringIDs
                }
            }
        };
```

We get this:
```csharp
        return new LedgerEntryContractData
        {
            LastModifiedLedgerSeq = 10000,
            LedgerExtensionV1 = _ledgerExtensionV1,
            Key = new SCString("key 1"),
            Value = new SCUint64(1000000),
            Contract = new SCContractId("CAC2UYJQMC4ISUZ5REYB2AMDC44YKBNZWG4JB6N6GBL66CEKQO3RDSAB"),
            Durability = ContractDataDurability.Create(ContractDataDurability.ContractDataDurabilityEnum.PERSISTENT),
            ExtensionPoint = new ExtensionPointZero()
            Liabilities = new Liabilities(100, 200), // From ExtensionV1
            NumberSponsored = 5, // From ExtensionV2
            NumberSponsoring = 7, // From ExtensionV2
            SignerSponsoringIDs = signerSponsoringIDs // From ExtensionV2
        };
```

This question counts for multiple occurrences.

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/TransactionTest.cs
> +                .SetSorobanTransactionData(sorobanData)
Can you also do a transaction with for example the Dart SDK and then read out that transaction with the .NET SDK? Or did you already do/check that?

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk-test/operations/SetOptionsOperationTest.cs
> +            var signer = SignerUtil.Ed25519PublicKey(KeyPair.FromSecretSeed("SA64U7C5C7BS5IHWEPA7YWFN3Z6FE5L6KAMYUIT4AQ7KVTVLD23C6HEZ"));
Can you add this in the `changelog.md`?

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/ConfigSettingContractBandwidthV0.cs
> +public class ConfigSettingContractBandwidthV0 : LedgerEntryConfigSetting
Can't this just be named `ConfigSettingContractBandwidth`?

This question counts for multiple occurrences.

2024-01-11 12:19 UTC, jopmiddelkamp commented on stellar-dotnet-sdk/TrustlineAsset.cs
> +                // TODO PoolID implementation
Is it a lot of work to add this into the PR?

2024-01-11 12:26 UTC, cuongph87 commented on stellar-dotnet-sdk/ConfigSettingContractBandwidthV0.cs
> +public class ConfigSettingContractBandwidthV0 : LedgerEntryConfigSetting
I thought about it, but wasn't sure if they would add V1 at some point.

2024-01-12 02:41 UTC, cuongph87 commented on stellar-dotnet-sdk-test/LedgerEntryTest.cs
> +            Key = new SCString("key 1"),
No, we can't, as the "generated" Key and Value fields are SCVal, not SCString/SCUint64.

2024-01-12 03:20 UTC, cuongph87 commented on stellar-dotnet-sdk-test/LedgerEntryTest.cs
> +            ExtensionV2 = new AccountEntryExtensionV2
I actually thought about it, was wondering if they wanted to "isolate" the extensions in the original schemes for a reason, beside memory optimization.

2024-01-12 04:22 UTC, cuongph87 commented on stellar-dotnet-sdk-test/TransactionTest.cs
> +                .SetSorobanTransactionData(sorobanData)
The Dart SDK doesn't have support for those yet. But for almost every test, I always try to decode the XDR base64 string in the Lab to check it's valid or not. Do you think it's relevant?

2024-01-17 07:59 UTC, jopmiddelkamp approved these changes

2024-01-19 07:40 UTC, merged